- action:
  - service: shell_command.set_hdmi_1
  alias: Set Switch to Chromecast
  hide_entity: true
  id: '1497064432776'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Chromecast
- action:
  - service: shell_command.set_hdmi_2
  alias: Set Switch to Xbox
  hide_entity: true
  id: '1497064544761'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Xbox
- action:
  - service: shell_command.set_hdmi_3
  alias: Set Switch to Rack Computer
  hide_entity: true
  id: '1497064582862'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Rack Computer
- action:
  - service: shell_command.set_hdmi_4
  alias: Set Switch to Input 4
  hide_entity: true
  id: '1497064642115'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Input 4
- id: '1497064647890'
  alias: Lights off when Media plays
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    platform: state
    to: playing
  action:
  - entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.switchmate
    service: switch.turn_off
  - data:
      entity_id: switch.aeotec_zw096_smart_switch_6_switch
    service: switch.turn_off
- action:
  - service: light.turn_on
    entity_id: light.living_room
  alias: Light on when Media Pauses
  id: '1497064640789'
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi, media_player.apple_tv
    platform: state
    from: playing
    to: paused
- id: '1497064640799'
  alias: Lights on When Media Off
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    platform: state
    to: 'off'
  action:
  - entity_id: group.all_lights
    service: light.turn_on
  - data:
      entity_id: switch.switchmate
    service: switch.turn_on
  - data:
      entity_id: switch.aeotec_zw096_smart_switch_6_switch
    service: switch.turn_on
- action:
  - service: shell_command.hdmi_init
  alias: Set HDMI baud rate on start
  hide_entity: true
  id: '1597064432776'
  trigger:
  - platform: homeassistant
    event: start
- id: '1497066640796'
  alias: Lights When Media Idle
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    platform: state
    to: idle
  action:
  - entity_id: group.all_lights
    service: light.turn_on
  - data:
      entity_id: switch.switchmate
    service: switch.turn_off
  - data:
      entity_id: switch.aeotec_zw096_smart_switch_6_switch
    service: switch.turn_off
- id: '1534802208342'
  alias: Home Scene at Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data:
      entity_id: scene.home
    service: scene.turn_on
- id: '1534802350246'
  alias: Away Scene When Everyone is Away
  trigger:
  - entity_id: group.all_devices
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: scene.away
    service: scene.turn_on
- id: '1534802695839'
  alias: Home Scene When Someone Gets Home
  trigger:
  - entity_id: group.all_devices
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: scene.home
    service: scene.turn_on
- id: '1538745290868'
  hide_entity: true
  alias: Launch Kore on Ryans phone when Kodi starts
  trigger:
  - entity_id: media_player.kodi
    platform: state
    to: idle
  condition:
  - condition: state
    entity_id: device_tracker.ryan_pixelxl
    state: home
  action:
  - data:
      event: launch_kodi
    service: ifttt.trigger
