- action:
  - service: shell_command.set_hdmi_1
  alias: Set Switch to Chromecast
  hide_entity: true
  id: '1497064432776'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Chromecast
- action:
  - service: shell_command.set_hdmi_2
  alias: Set Switch to Xbox
  hide_entity: true
  id: '1497064544761'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Xbox
- id: '1497064582862'
  alias: Set Switch to Rack Computer
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Rack Computer
  action:
  - service: shell_command.set_hdmi_3
  - data:
      mac: 1C-6F-65-3D-E6-7E
    service: wake_on_lan.send_magic_packet
  - data:
      entity_id: switch.entry_light
    service: switch.turn_off
  hide_entity: true
- action:
  - service: shell_command.set_hdmi_4
  alias: Set Switch to Input 4
  hide_entity: true
  id: '1497064642115'
  trigger:
  - entity_id: input_select.hdmi_switch
    platform: state
    to: Input 4
- id: '1497064647890'
  alias: Lights off when Media plays
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    platform: state
    to: playing
  action:
  - entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.entry_light
    service: switch.turn_off
  - data:
      entity_id: switch.party_cube
    service: switch.turn_off
- action:
  - service: light.turn_on
    entity_id: light.living_room
  alias: Light on when Media Pauses
  id: '1497064640789'
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    platform: state
    from: playing
    to: paused
- id: '1497064640799'
  alias: Lights on When Media Off
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    from: playing
    platform: state
    to: 'off'
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    from: paused
    platform: state
    to: 'off'
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    from: idle
    platform: state
    to: 'off'
  action:
  - entity_id: group.all_lights
    service: light.turn_on
  - data: {}
    service: switch.turn_on
- action:
  - service: shell_command.hdmi_init
  alias: Set HDMI baud rate on start
  hide_entity: true
  id: '1597064432776'
  trigger:
  - platform: homeassistant
    event: start
- id: '1497066640796'
  alias: Lights When Media Idle
  trigger:
  - entity_id: media_player.bill_bill_bill, media_player.kodi
    platform: state
    to: idle
  action:
  - data:
      transition: '5'
    entity_id: group.all_lights
    service: light.turn_on
  - data:
      entity_id: switch.entry_light
    service: switch.turn_off
  - data:
      entity_id: switch.party_cube
    service: switch.turn_off
- id: '1534802208342'
  alias: Home Scene at Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - condition: state
    entity_id: group.all_devices
    state: home
  action:
  - data:
      entity_id: scene.home
    service: scene.turn_on
- id: '1534802350246'
  alias: Away Scene When Everyone is Away
  trigger:
  - entity_id: group.all_devices
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: scene.away
    service: scene.turn_on
- id: '1534802695839'
  alias: Home Scene When Someone Gets Home
  trigger:
  - entity_id: group.all_devices
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: scene.home
    service: scene.turn_on
- id: '1538745290868'
  alias: MQTT Publish Kodi Idle
  trigger:
  - entity_id: media_player.kodi
    platform: state
    to: idle
  condition: []
  action:
  - data:
      payload: idle
      topic: kodi
    service: mqtt.publish
  hide_entity: true
- id: '1544655095616'
  alias: MQTT Publish Home Assistant Update
  trigger:
  - entity_id: updater.updater
    platform: state
  condition: []
  action:
  - data:
      payload: '{{ states.updater.updater.state }}'
      topic: updater
    service: mqtt.publish
  hide_entity: true
- id: '1544786155171'
  alias: Dim Red When Motion Downstairs
  hide_entity: true
  trigger:
  - entity_id: binary_sensor.downstairs_multisensor_sensor
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      brightness: 20
      rgb_color:
      - 255
      - 0
      - 0
    service: light.turn_on
    entity_id: all
- id: '1544786382057'
  alias: Lights Off When No Motion
  trigger:
  - entity_id: binary_sensor.downstairs_multisensor_sensor
    platform: state
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: all
  hide_entity: true
- id: '1552071710423'
  alias: Chromecast State Change
  trigger:
  - entity_id: media_player.bill_bill_bill
    platform: state
  condition: []
  action:
  - data:
      entity_id: input_select.hdmi_switch
      option: Chromecast
    service: input_select.select_option
- id: '1552075932333'
  alias: 'Night when sleeping '
  trigger:
  - platform: mqtt
    topic: scene/night
  condition: []
  action:
  - data:
      entity_id: scene.night
    service: scene.turn_on
- id: '1552695569187'
  alias: Kodi State Change
  trigger:
  - entity_id: media_player.kodi
    platform: state
  condition: []
  action:
  - data:
      entity_id: input_select.hdmi_switch
      option: Rack Computer
    service: input_select.select_option
- id: '1556663947098'
  alias: Ryan Home
  trigger:
  - entity_id: device_tracker.ryan_pixel_xl
    for: '30'
    platform: state
    to: home
  condition: []
  action:
  - data:
      payload: home
      topic: device/ryan
    service: mqtt.publish
