homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 164
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  # Make pretty
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Show Map
# map:

# Shopping List
shopping_list:

# iOS
ios:

# Enables configuration UI
config:

http:
  api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Record states for history
recorder:
# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key

input_select: !include input_selects.yaml 
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
automation: !include automations.yaml
shell_command: !include shell_commands.yaml
mqtt: !include mqtt.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
media_player: !include media_player.yaml 
notify: !include notify.yaml
wemo: !include wemo.yaml
script: !include scripts.yaml
# zwave: !include zwave.yaml
wake_on_lan:
