- platform: asuswrt
  host: 192.168.1.1
  username: admin
  password: !secret router_password
  interval_seconds: 12
  consider_home: 240
  new_device_defaults:
    track_new_devices: False
    hide_if_away: True
- platform: owntracks
