version: '2'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:0.76.2
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/hdmi:/dev/hdmi
      - /dev/zwave:/dev/zwave
    restart: unless-stopped
    network_mode: host
